import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <Link
          href="/"
          className="text-xl hover:text-orange-800 absolute bottom-5 right-1/2 translate-x-1/2"
        >
          Back to Home
        </Link>
      </body>
    </html>
  );
}
